### ISSUE TITLE
Placeholder & ellipsis text

### ISSUE THREAD

**Issue by cara-tm** [picocss/pico#101]
All field placeholders could be enhanced with text ellipsis:

    input:not([type=checkbox]):not([type=radio]):not([type=range]):not([type=file])::placeholder {
        text-overflow:ellipsis
    }

**Comment by lucaslarroche** [comment]
Nice find too.
I will ship this improvement.

**Comment by lucaslarroche** [comment]
After some tests, I will not ship it as it's not working on :focus. for Chrome and Safari

https://user-images.githubusercontent.com/23470684/147845812-9d573e0b-cd84-4db7-b999-fe2f9ef0b3d1.mov
