### ISSUE TITLE
[Feature request] Header, main and footer to be containers in classed version

### ISSUE THREAD

**Issue by ptcane** [picocss/pico#107]
It would be great to have the benefits of class-less version (cleanest, classless HTML) but with the extra features of classed available as required.

I suggest applying the `header`, `main` and `footer` centered viewport container css by default to the classed css (surely the most popular default choice) with the option via classes to 'decontainer' or 'fluid' if required.

This would also (I suggest in the `pico` spirit) mean only one CSS file needs to be maintained, documented, etc.

**Comment by jubishop** [comment]
We wouldn't want to delete existing variants because that would be a breaking change and I don't think we should just keep adding more.  I suggest adding some documentation examples on how to simply make any variant you want with the variables in _variables.scss.   (this is what I've done).

**Comment by ptcane** [comment]
Use of a preprocessor is something I want to avoid.

For anyone else looking to do this as things stand and without sass, my current solution is to import the standard Pico CSS at the top of a CSS file in which I've copied the relevant lines from the classless version.

**Comment by ptcane** [comment]
I'll close this, but for anyone looking for the same, here's what I use:

```
@import url("https://unpkg.com/@picocss/pico@latest/css/pico.min.css");

body > header,
body > main,
body > footer {
  width: 100%;
  margin-right: auto;
  margin-left: auto;
  padding: var(--block-spacing-vertical) var(--block-spacing-horizontal);
}

@media (min-width: 576px) {
  body > header,
body > main,
body > footer {
    max-width: 510px;
    padding-right: 0;
    padding-left: 0;
  }
}
@media (min-width: 768px) {
  body > header,
body > main,
body > footer {
    max-width: 700px;
  }
}
@media (min-width: 992px) {
  body > header,
body > main,
body > footer {
    max-width: 920px;
  }
}
@media (min-width: 1200px) {
  body > header,
body > main,
body > footer {
    max-width: 1130px;
  }
}
```
