### ISSUE TITLE
Dark / Light Theme buttons, any workaround to make them work if the user has noscript installed?

### ISSUE THREAD

**Issue by Jieiku** [picocss/pico#109]
If a user has noscript installed then the Dark / Light switch buttons do not function.

This is not really an issue or bug. Anyone using noscript is going to be familiar with whitelisting / trusting things.

This is just a question if there is a way we could allow these Dark and Light theme switches to work even if noscript is installed.

If I figure out a workaround myself I will be sure to follow up here with it.

ALSO! Beautiful lightweight framework, very excited to have found this! implementing it now!

**Comment by Anachron** [comment]
Only if you add an url that lets the server send a specific theme. How else do you want to do it without js?

**Comment by Jieiku** [comment]
Yeah I figured it would take a trick or something. So I really appreciate your response.
So theres a way I can do it if I split the css into two different ones?

My initial idea was to use a cookie that sets which theme you want.

**Comment by lucaslarroche** [comment]
It can be 2 static pages.
For example :
- index-light.html with `<html data-theme="light">`
- index-dark.html with `<html data-theme="dark">`
