### ISSUE TITLE
Padding on date input moves hidden date icon in chromium

### ISSUE THREAD

**Issue by Xenira** [picocss/pico#110]
The change in https://github.com/picocss/pico/blame/master/scss/content/_form-alt-input-types.scss#L44 moves the hidden browser date icon to the left. This causes the pico css icon to not work correctly. You need to click to the left of it to open the calendar.

See https://picocss.com/docs/forms.html for example.

Tested in current Vivaldi and Edge (both chromium).
Firefox is not affected.

https://user-images.githubusercontent.com/1288524/148003101-19fe9a4a-eb43-4041-959d-6494f3b56141.mov

**Comment by lucaslarroche** [comment]
Thank you.
You are right; there is a bug here.
I will try to ship a patch quickly.

**Comment by lucaslarroche** [comment]
Hi @Xenira, 

I believe it's fixed.
Can you check on this page:
https://picocss.github.io/pico/docs/forms.html

**Comment by Xenira** [comment]
Thanks for the fast Fix.
Yes its working correctly now.

**Comment by natiT** [comment]
> Hi @Xenira,
> 
> I believe it's fixed. Can you check on this page: https://picocss.github.io/pico/docs/forms.html

Fixed on this part! Hopefully it will be part of the next release!
