### ISSUE TITLE
Responsive grid without bootstrap?

### ISSUE THREAD

**Issue by Jieiku** [picocss/pico#117]
I was looking at the grid example and documentation (https://picocss.com/docs/grid.html)

particularly this:

> A complete grid system in flexbox, with all the ordering, offsetting and, breakpoints utilities, can be heavier than the total size of the Pico library. Not really in the Pico spirit.

but then those notes link to bootstrap or flexbox grid for prototyping... those are too big.
I dont want to use something just to prototype.

I want to be able to make a 3, 4, 5, or 6 column horizontal grid anywhere.... and have it just work! responsive and looks great on desktop or mobile.

Then it links CSS grid generator, layoutit, griddy. These seem to make grids on a case by case basis, also these grids do not seem to stack vertically, they only shrink. If a page width is narrow enough you want the items to stack vertically more and more as the page becomes more narrow! So that they are still large enough to be able to see on mobile.

Then you have the grid used by milligram, very light weight, and unless i am missing something works great!
https://github.com/milligram/milligram/blob/master/src/_Grid.sass

A great example of this can also be seen here (They stack vertically as the page width becomes more narrow):
https://milligram.io/#grids
https://picnicss.com/documentation#grids

This is not meant to be a criticism, its a post made out of confusion as to why pico does not use something similar, pico seems to have plenty of flavours: classless, fluid, slim, etc... but no grid option, not even a lightweight grid option like that of milligram. (only links that are like hey go here and use this)

milligram does not appear to be maintained anymore, but pico is. so I absolutely plan to use pico if possible.

I am going to try using pico with the grid implementation of milligram, but I wonder if such a combination could be officially supported by pico, because the more people using the same grid, the more attention and testing that particular grid implementation will receive.

As pointed out by Pico docs, most grids are heavy.... but clearly not all of them as evident by the milligram grid system... so why not support and further refine a nice lightweight grid system.

even pure.css supports a grid system, they just dont bundle it: https://unpkg.com/purecss@2.0.6/build/grids-responsive-min.css

**Comment by Jieiku** [comment]
Just wanted to post that I am Frankensteining something together, if it works really well I will submit it as a pull request as another flavor for pico.css

**Comment by Jieiku** [comment]
Pull request is up for anyone wanting to check it out: https://github.com/picocss/pico/pull/120

I will add to the example documentation next, and add that to the pull request.

**Comment by lucaslarroche** [comment]
Hi @Jieiku, 

I have seen your PR (#120).
As Pico claim to be "Responsive everything", if we introduce a grid in Pico, it must be fully responsive with the option to define a column size according to the breakpoint.

**Comment by Jieiku** [comment]
sounds good, I will play around a bit more and see what the lightest weight one is that I can find and integrate.
