### ISSUE TITLE
Request: Using vars for Grid/Breakpoints

### ISSUE THREAD

**Issue by ethanpil** [picocss/pico#118]
I'm curious to hear thoughts about making the grid and breakpoints using adjustable variables at run time?  Some benefits include:

- not locked in to the `lg` breakpoint for grid
- ability to use non default breakpoints in projects without recompiling

**Comment by lucaslarroche** [comment]
I would like a have a propper grid system in Pico.

> If we introduce a grid in Pico, it must be fully responsive with the option to define a column size according to the breakpoint.  
> #117

Not so easy to find the right balance as I would like to avoid a gigantic component (to stay in the lightweight side).

I will close this issue as we already have:
- a [PR opened here](#120)
- an [issue here](#117)

**Comment by ethanpil** [comment]
@lucaslarroche  My question was a bit different than those requests. I am specifically referring to these lines of code below and wondering if there is a better way... Hardcoding the existing Grid breakpoint at `lg` seems a bit restrictive and arbitrary. I 'm not requesting a full on grid system, which I agree is too much. Just some adaptation of the existing grid.  Perhaps something as simple as using  (an overwriteable) CSS custom property to decide the breakpoint.

`--grid-breakpoint: lg`

Somewhere here:
1. https://github.com/picocss/pico/blob/6b05b161ef3a00e2e9b1135b88e302a4c32f4519/scss/layout/_grid.scss#L15
