### ISSUE TITLE
Adding scaling to button on hover and on click

### ISSUE THREAD

**Issue by jochemvogel** [picocss/pico#121]
Currently, when you hover over a button, it'll get the following styles:

```css
--background-color: var(--primary-hover);
--border-color: var(--primary-hover);
--box-shadow: var(--button-hover-box-shadow, 0 0 0 rgba(0, 0, 0, 0));
```

I always prefer to add a `transform: scale(1.015)` to my buttons on hover. When a user hovers over the button, it will be very clear that you can interact with it.

The same with the `:active` class. On click I prefer a `transform: scale(0.975)`.

Those `1.015` and `0.975` values are just an example. Doesn't really matter how much. I just want to make clear that adding those small things will probably improve the UX.

I'm ok with implementing it myself, but I just first wanted to know is if it something you like to have? Maybe it's something I like, but others don't and because of that not a good feature to implement. Lmk! 🙂

**Comment by lucaslarroche** [comment]
Hi @jochemvogel, 
I think it's very specific.
I prefer not to add this to the default theme.
But I could be open to a PR with new CSS vars: `--button-transform`, `--button-hover-transform`, `--button-active-transform`
