### ISSUE TITLE
SVG used as background-image not changing color in dark mode

### ISSUE THREAD

**Issue by mcordova1967** [picocss/pico#122]
Hello, we are using a couple of Bootstrap SVG icons in our CSS, like:

background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-trash' viewBox='0 0 16 16'%3E%3Cpath d='M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z'/%3E%3Cpath fill-rule='evenodd' d='M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z'/%3E%3C/svg%3E");

The icons are not changing the color when dark mode is set, is there anything we should add to our custom CSS after importing pico.css?

Thank you very much,
Martin

**Comment by cara-tm** [comment]
I tried to add a style (with `prefers-color-scheme`) declaration within the SVG icons without any success

**Comment by kvetoslavnovak** [comment]
I believe you cannot use css variable with url(). But css mask is the way to go. 
You can read more in this great article  [Coloring SVGs in CSS Background Images](https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images?__cf_chl_captcha_tk__=w5G.Y.ZcnRzuGuareocexQKVwODqFuIv.jp9PxYbfKU-1641510101-0-gaNycGzNB30)

**Comment by lucaslarroche** [comment]
Yes, we can't dynamically change a background image SVG color.
That's why Pico has [light icons](https://github.com/picocss/pico/blob/master/scss/themes/default/_light.scss#L129) and [dark icons](https://github.com/picocss/pico/blob/master/scss/themes/default/_dark.scss#L129).
