### ISSUE TITLE
Feature request: Add the pressed, or 'active' button as an element

### ISSUE THREAD

**Issue by marek-lach** [picocss/pico#124]
This is a very cool project, first of all. What it doesn't seem to have yet is the 'actively pressed' button, or an active tab variant. Somewhat akin to this from the Semantic UI toolkit:

![actively_pressed_button](https://user-images.githubusercontent.com/45913977/148563813-b60aae3f-29e6-4666-ab61-3cbe1dd6a83a.png)

**Comment by lucaslarroche** [comment]
We could use [aria-current](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) for that.
What do you think?

**Comment by marek-lach** [comment]
> We could use [aria-current](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) for that. What do you think?

Yes, it seems [aria-current](https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaCurrent) could be the syntax, then just the visual representation would have to be created for it also...
