### ISSUE TITLE
Input type date and input type time do not show browser picker on mouse click

### ISSUE THREAD

**Issue by kvetoslavnovak** [picocss/pico#126]
input type="date" and input type="time" do not work on click to show default browser picker. Only small part of the input reacts to the mouse click as shown in the pictures bellow. (Chrome, Pop!_OS)
It looks like you are covering the default clickable icons over with your own so pickers are not accessible.
Flowing brief check of pico.css I guess the error is because you are probably using this rather disputable pattern to use your own icons:
`````
input[type="date"]::-webkit-calendar-picker-indicator {
   ...
   background-image: var(--icon-date);
   ...
}
`````

But probably better and following accessibility rules may be this solution:
`````
input[type="date"]::-webkit-calendar-picker-indicator {
   ...
   background: var(--icon-date) no-repeat;
   ...
}
`````
This way you can literary swap the default icons with your owns instead of "covering" them over and making them inaccessible.. 

![Input1](https://user-images.githubusercontent.com/5719547/148611658-1b84521f-b0e9-4c14-81b9-d58829bd10e5.jpg)
![Input2](https://user-images.githubusercontent.com/5719547/148612040-92c9fce4-552b-4ee7-af9c-ba798258bf78.jpg)

**Comment by jubishop** [comment]
Thanks for raising this I noticed this today too

**Comment by lucaslarroche** [comment]
Hi @kvetoslavnovak, 

Is #110 the same issue? 

I believe it's fixed [here](112).
Can you check on this page:
https://picocss.github.io/pico/docs/forms.html

**Comment by lucaslarroche** [comment]
```CSS
input[type="date"]::-webkit-calendar-picker-indicator {
   ...
   background: var(--icon-date) no-repeat;
   ...
}
```
That would impact only Chrome.

**Comment by kvetoslavnovak** [comment]
Hi, I have checked the page and there it is working correctly.
Thank you very much.
