### ISSUE TITLE
dialog article max-width

### ISSUE THREAD

**Issue by prologic** [picocss/pico#127]
What's the purpose of these media selectors and `max-width` on the `dialog article` element?

https://github.com/picocss/pico/blob/6b05b161ef3a00e2e9b1135b88e302a4c32f4519/css/pico.classless.css#L1897-L1906

In our use case, this causes the dialog to overflow the bounds of the view port.

With `max-width` enabed:

<img width="1392" alt="Screen Shot 2022-01-09 at 23 54 04" src="https://user-images.githubusercontent.com/1290234/148685168-0ac8d918-9f08-4398-b74e-38df9755e895.png">

Without:

<img width="1392" alt="Screen Shot 2022-01-09 at 23 54 28" src="https://user-images.githubusercontent.com/1290234/148685184-47a3deb8-1c8b-482f-98cd-00d6e37ca1a6.png">

**Comment by lucaslarroche** [comment]
Hi @prologic, 

It's a common practice to constraint the width of a modal to avoid gigantic modal on large screens.
I don't see a bug here. 
What is your problem? Is it because your page viewport does not appear to be centered with the modal?

**Comment by prologic** [comment]
The problem here as you can see in the 1st screenshot, it the modal itself is outside of the bounds of the viewport.

This I believe to be a _slight_ bug?

**Comment by prologic** [comment]
Specifically the top and bottom are getting cut off as is the contained image. It _might_ be something we're doing wrong though in our use of the `<dialog>` so I not 100% sure it's a bug here to be fair.

**Comment by lucaslarroche** [comment]
Ok, I was looking at the width... but looking at the height: yes we might have a bug (unhandled case).
I did some tests and if the content is taller than the screen we don't have any scroll.

Note for myself:
```CSS
max-height: calc(100vh - var(--spacing) * 2);
overflow: auto;
```

**Comment by cara-tm** [comment]
Exact ! You were faster than me; I was looking a solution:

    dialog article {
        overflow-y: auto;
        max-width: 510px;
        max-height: calc(100% + var(--block-spacing-vertical))
    }
