### ISSUE TITLE
Feature request: Allow role="button" on Span

### ISSUE THREAD

**Issue by LokiMidgard** [picocss/pico#128]
Currently role="button" is only available on the `<a/>` tag.

The documentation says
> Use `<a role="button">` if you need an inline element.

However this will only work correctly if you set the href.

If you only need a JavaScript function to be executed, and don't want to excedently change the anchor of the location (or anything else on it), Span would propably work better.

*Or eny other element you cen set a click handler and that will not disable by default*

**Comment by lucaslarroche** [comment]
Hi @LokiMidgard,

Good one.
There is no restriction on using [`role="button"` on other HTML elements](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role).
I changed the CSS from `a[role="button"]` to `[role="button"]`.

I will ship this small change in the next release.
