### ISSUE TITLE
🐛 When use <fieldset> to disabled all input, disabled style no work

### ISSUE THREAD

**Issue by Gaubee** [picocss/pico#143]
here is how `<fieldset>` work: [demo](http://jsfiddle.net/xdkf9b8j/1/)

I think we should use `:disabled` alertnative `[disabled]`

**Comment by lucaslarroche** [comment]
@Gaubee,
Thank you.
I didn't know about this behavior.
This issue will be fixed in the [next release](https://github.com/picocss/pico/issues/155).
