### ISSUE TITLE
Improve installation via Composer

### ISSUE THREAD

**Issue by vardumper** [picocss/pico#146]
I am working on a PHP-based (Slim4) project, and don't want to add an additional layer (node package manager etc) since everything I need for my project can be done in PHP. I use `scssphp/scsspsp` to compile scss into css – so all I wanted was to pull in the scss files. 

I was able to do that, by adding the repo to my composer.json like this:
```
...
	"repositories" : [{
		"type" : "package",
		"package" : {
			"name" : "picocss/pico",
			"version" : "1.4.4",
			"source" : {
				"url" : "https://github.com/picocss/pico",
				"type" : "git",
				"reference" : "master"
			}
		}
	}
...
```

After that I could install pico.css with `composer require picocss/pico` 

If there would have been a composer.json in the project and picocss would be listed on packagist, installation would have worked without that step.

**Comment by lucaslarroche** [comment]
After more thinking. I agree. Pico should have a config file for composer.

**Comment by vardumper** [comment]
For me this topic is solved. Feel free to close the ticket. 
Roundup for anybody interested or stumbling over this ticket https://erikpoehler.com/2022/02/27/build-watch-sass-files-with-php/
