### ISSUE TITLE
Need example of how to load with svelte-kit from node_modules

### ISSUE THREAD

**Issue by ralyodio** [picocss/pico#153]
Please provide.

**Comment by ralyodio** [comment]
https://stackoverflow.com/questions/70932166/how-do-i-load-pico-css-from-node-modules-in-a-svelte-kit-app

**Comment by kvetoslavnovak** [comment]
I am using import from the CDN in the original HTML. Works great and I guess it is the most efficient way for users as well.

**Comment by appauldev** [comment]
Here's what I did to integrate Pico to SvelteKi:

1. In the root folder of the SvelteKit project, run `npm install @picocss/pico` (as seen on their [docs page](https://picocss.com/docs/))
2. Once installed, add `import  @picocss/css` to the `<script></script>` portion of your `__layout.svelte`. This makes Pico accessible to all your pages using this default layout. **NOTE:** you need to create `__layout.svelte` first inside `src/routes` if you do not have this file in your project folder. Read the [official docs](https://kit.svelte.dev/docs/layouts) to learn more about layouts in SvelteKit.
3. Alternatively, if you only plan to use Pico to some of your pages, just add `import  @picocss/css` to the `<script></script>` portion of the pages where you want to use Pico. 

After these, Pico will be automatically applied to the HTML elements of your page :)

Another option is to [download](https://picocss.com/docs/) the Pico css files and link the css files manually inside the `<head></head>` portion of `src/app.html` or install it via CDN in a similar manner as suggested by @kvetoslavnovak. Note that these methods will also apply Pico to all your pages. 

I hope these would help you. Good luck and happy coding!!!
