### ISSUE TITLE
Long tooltip inside article/card not working properly

### ISSUE THREAD

**Issue by Manuel-Steinberg** [picocss/pico#156]
See demo on Codepen: https://codepen.io/Manuel-Steinberg/full/GROrRbj

Tooltip will be trimmed at article/card edge.
![image](https://user-images.githubusercontent.com/11491106/152792065-ea43ab30-9bac-413c-a72d-391980390249.png)

**Comment by lucaslarroche** [comment]
@Manuel-Steinberg,
Nice find. Thank you.
This issue will be fixed in the [next release](https://github.com/picocss/pico/issues/155).

**Comment by Manuel-Steinberg** [comment]
You´re welcome. Awesome work.
