### ISSUE TITLE
sessionStorage for the data-theme attribute

### ISSUE THREAD

**Issue by moodworks** [picocss/pico#158]
Hello,

maybe I'm missing something, but is there a way save the html `data-theme` attribute when user clicks on a internal link?

Thanks

**Comment by vardumper** [comment]
Look at the examples, they use this https://picocss.com/examples/js/minimal-theme-switcher.js

Sessions are server side. CSS and ThemeSwitcher are client side, so if you want it on the server side, you have to somehow send it (via GET/POST), etc. which to me seems unnecessary. Store it in the browsers localStorage like this:
```
const themeSwitcher = {
  // Config
  buttonsTarget: "a[data-theme-switcher]",
  buttonAttribute: "data-theme-switcher",
  rootAttribute: "data-theme",

  // Init
  init() {
    let osTheme = ((window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light');
    let useTheme = localStorage.getItem("theme") || osTheme;
    document
      .querySelector("html")
      .setAttribute(
      this.rootAttribute,
      useTheme
    );
    document.querySelectorAll(this.buttonsTarget).forEach(
      function (button) {
        button.addEventListener(
          "click",
          function (event) {
            event.preventDefault();
            document
              .querySelector("html")
              .setAttribute(
                this.rootAttribute,
                event.target.getAttribute(this.buttonAttribute)
              );
              localStorage.setItem('theme', event.target.getAttribute(this.buttonAttribute)); // saves current theme
          }.bind(this),
          false
        );
      }.bind(this)
    );
  },
};

// Init
themeSwitcher.init();
```

**Comment by reinerBa** [comment]
You can bind onclick listeners on internal links to do so. This cannot be done with css and pico is only a css library.

**Comment by lucaslarroche** [comment]
@moodworks, 
As @vardumper and @reinerBa pointed out, saving the theme can't be done in CSS.
You have to use JavaSript.

The [next release](https://github.com/picocss/pico/pull/155) will save the theme in localStorage for the documentation pages.

The code used is here:
https://github.com/picocss/pico/blob/dev/docs/js/src/theme-switcher.js
