### ISSUE TITLE
Buttons style do not reset after click or submission with click

### ISSUE THREAD

**Issue by kvetoslavnovak** [picocss/pico#161]
Hi, 
I encounter this problem playing with autocomplete dropdown tests using form. But later I discovered this is a problem of all Pico buttons and input submit buttons, 
When you click the button in Pico and it makes it jobs it does not reset style to be unclicked again ad stays active. Try this simple example of use case or Pico website: https://picocss.com/docs/buttons.html
```
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
</head>  
<body>
<main class="container">
<h1>The button Element</h1>
<button type="button" onclick="alert('Hello world!')">Click Me!</button>
</main>
</body>
</html>
```
Sorry if this was meant to be a default behavior, I am not sure what is right and proper accessibility way.

**Comment by lucaslarroche** [comment]
Hi @kvetoslavnovak, 

AFAIK, we can't block the button after submitting in CSS.
The state change must be done in javascript, and Pico does not support JavaScript.

But Pico natively manages the `disabled` and `aria-busy` properties. 
Here is an example of how you could transform your button after the submit:

_Before submit:_
```HTML
<button type="submit">Submit</button>
````
_After submit:_
```HTML
<button type="submit" aria-busy="true" disabled>Please wait</button>
````

**Comment by kvetoslavnovak** [comment]
Thank you very much for your explanation.
