### ISSUE TITLE
Right text input on nav misalign the links on the left and viceversa

### ISSUE THREAD

**Issue by nitodico** [picocss/pico#162]
Setting a basic navbar with a right search box will misalign the links of a nav bar, basically because the input has a bottom margin that modifies the nav height

![imagen](https://user-images.githubusercontent.com/49000973/154543954-3a2d9b81-24e3-472e-b91d-1db1b98181b7.png)

```html
<nav>
<ul>
<li>Home</li>
<li>Products</li>
<li>Contact</li>
</ul>

<ul>
<li><input type='text'</li>
</ul>
</nav>
```

It can be manually fixed with `nav li input{border-bottom:0}`

**Comment by lucaslarroche** [comment]
@nitodico, 
Nice find. Thank you.
This issue will be fixed in the [next release](155).
