### ISSUE TITLE
unminified css and noticed Light theme is listed once but the dark theme is listed twice, what is the purpose of doing it this way?

### ISSUE THREAD

**Issue by Jieiku** [picocss/pico#167]
Including a complete copy of the dark theme is the largest thing increasing the size of the css file, I am sure there is a technical reason for doing it this way, but I am hoping somebody can explain it to me.

Is there no way to create the dark theme once and then refer to it again later?

I really appreciate whoever can explain this to me, thank you.

```css
[data-theme="light"], :root:not([data-theme="dark"]) {
    color-scheme: light;
    --background-color:  #fff;

...

@media only screen and (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
    color-scheme: dark;
    --background-color:  #11191f;

...

[data-theme="dark"] {
    color-scheme: dark;
    --background-color:  #11191f;
```

**Comment by Jieiku** [comment]
I found the explanation in the default.scss file one is for dark theme automatic and one is for dark theme forced like if the user manually sets it to use dark mode.... its a real shame that the entire thing has to be duplicated in the css file for this.

**Comment by Anachron** [comment]
Maybe we can do something like 

https://web.dev/prefers-color-scheme/

**Comment by Jieiku** [comment]
That appears to be what is done in the default.scss file for the automatic dark mode, but then the entire dark theme is duplicated for the forced dark mode:

```css
// Light theme (Default)
// Can be forced with data-theme="light"
@import "default/light";

// Dark theme (Auto)
// Automatically enabled if user has Dark mode enabled
@import "default/dark";
@media only screen and (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    @include dark;
  }
}

// Dark theme (Forced)
// Enabled if forced with data-theme="dark"
[data-theme="dark"] {
  @include dark;
}
```

**Comment by Anachron** [comment]
I'm new to media theming but if I read the link correctly thats not needed. 

I could paste the whole post here but whats the point?

**Comment by lucaslarroche** [comment]
@Jieiku,
Yes, as you already [spotted](https://github.com/picocss/pico/issues/167#issuecomment-1055154324): This allows us to manage both the "auto" version (`prefers-color-scheme`) and the forced version `[data-theme="dark"]`.
I haven't found a better way to do it 😐.
I'm not happy with this duplication either. But AFAIK, there is no other way.
I will close this issue.

**Comment by Jieiku** [comment]
I am not sure that this would work for every facet of pico, but here is what I did, and it does what I need it to:

https://github.com/Jieiku/abridge/blob/master/sass/abridge.scss

I also have a switcher:

https://github.com/Jieiku/abridge/blob/master/static/theme.js

https://github.com/Jieiku/abridge/blob/master/static/theme_button.js

you can see it all in action here: https://abridge.netlify.app/
