### ISSUE TITLE
Modal header text rendering as black in firefox

### ISSUE THREAD

**Issue by MxReaper** [picocss/pico#185]
Modal header text rendering as black in firefox in dark mode.
  
### Current Behavior
Modal header text is rendering as black in firefox 98.0.2

### Expected Behavior
Modal header text should be rendering as white. 

### Reproduction URL
https://codepen.io/mxreaper/pen/RwxKNVY

### Environment
Windows 10, Firefox 98.0.2

**Comment by kvetoslavnovak** [comment]
Same in Safari (iOS).

**Comment by MxReaper** [comment]
What from i see the examples/live demo don't use the header element. So you don't see the issue.

**Comment by lucaslarroche** [comment]
@MxReaper, thank you.
I was able to reproduce the bug on iOs.
The browser is setting a default color for the dialog element. I had to override it.
The fix will be shipped in the [next release](https://github.com/picocss/pico/pull/196).
