### ISSUE TITLE
Margins on article

### ISSUE THREAD

**Issue by prologic** [picocss/pico#2]
Hi,

The margins on `<article>` seem to be quite large on devices such as Laptops and Desktop. ON Mobile it looks great. Is there a reason these are as large as they are on larger devices? It really reduces the screen real estate for something like what you see on https://twtxt.net/ if you view this in a Browser on Desktop.

Or am I doing something horribly wrong? :)

Example attached.

<img width="1312" alt="Screen Shot 2020-07-24 at 11 06 26 AM" src="https://user-images.githubusercontent.com/1290234/88352709-0f185080-cd9e-11ea-8e37-4a24b707190b.png">

**Comment by lucaslarroche** [comment]
This is a deliberate choice.
[Typography](https://picocss.com/docs/#typography), [Container](https://picocss.com/docs/#containers) and [Cards](https://picocss.com/docs/#cards) provide responsive sizes and margins.

You can disable all responsive spacings in the [config file](https://github.com/picocss/pico/blob/master/scss/_variables.scss) ([line 16](https://github.com/picocss/pico/blob/master/scss/_variables.scss#L16)).

**Comment by prologic** [comment]
I guess my argument is that the spacings are too much for larger devices. The responsiveness is good but you end up wasting a lot of space? Maybe it's just me :)

**Comment by lucaslarroche** [comment]
I this case, you can fine tune the "spacing factor" in pico in the [config file ](https://github.com/picocss/pico/blob/master/scss/_variables.scss)([line 135](https://github.com/picocss/pico/blob/master/scss/_variables.scss#L135)).  🙂

For example: 
```SCSS
$spacing-factor: (
  xs: 1,
  sm: 1.125,
  md: 1.25,
  lg: 1.375,
  xl: 1.5
);
```

**Comment by lucaslarroche** [comment]
Here is an [example scss file](https://github.com/picocss/pico/blob/master/scss/pico.fluid.classless.scss) to compile your own pico version.

**Comment by prologic** [comment]
I _think_ I ended up doing this actually and [forked](https://github.com/prologic/picocss) (_even though I know nothing about sass!_) Thanks :)

**Comment by bard** [comment]
I felt the same margins on large screens, and since I wanted a CSS solution without build steps, the mention of SCSS almost made me look for a different micro framework. It turned out however that this can be easily achieved with CSS variables. Leaving this here in case someone stumbles on the same issue:

```css
      @media (min-width: 1200px) {
        body > footer,
        body > header,
        body > main,
        section {
          --block-spacing-vertical: calc(var(--spacing) * 2); /* default is var(--spacing) * 4 */
        }
      }
```
