### ISSUE TITLE
Header & Footer missing rounded corners on articles

### ISSUE THREAD

**Issue by GerdonAbbink** [picocss/pico#210]
### Current Behavior
On the latest version (v1.5.2) the header and footer on articles are missing rounded corners

### Reproduction URL
https://jsfiddle.net/7v15fo3w/

### Environment
macOS, Google Chrome (Version 102.0.5005.61)

**Comment by lucaslarroche** [comment]
Hi @GerdonAbbink, 
Thank you. 
It will be fixed in the next release.
