### ISSUE TITLE
`disabled='false'` shows pointer `not-allowed`

### ISSUE THREAD

**Issue by mwargan** [picocss/pico#216]
Please search for duplicate or closed issues first.
  
## Describe the issue

Elements with attribute `disabled='false'` remain showing with the pointer as `not-allowed`.
  
### Current Behavior
A concise description of the bug.

### Expected Behavior
Not to be disabled.

### Reproduction URL
https://jsfiddle.net/8Lvs0b79/1/

### Environment
Example: OS, versions, browser details.

**Comment by mwargan** [comment]
Oops my apologies, the HTML spec says that the mere presence of `disabled` equates to true, and the absence of it to `false`. https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attribute

**Comment by walterdavis** [comment]
I was just typing that all out for you!
