### ISSUE TITLE
Preview examples

### ISSUE THREAD

**Issue by thipages** [picocss/pico#25]
Hi,
In the preview ewamples, clicking on the color picker triggers the switch below.

**Comment by lucaslarroche** [comment]
Hi @thipages,
I couldn't see the bug.
Can you tell me more about your OS, device, browser?
Ideally, can you take a screenshot or a video capture?

**Comment by thipages** [comment]
Hi,
here is a [video](https://titsoft.com/shared/colorpicker.mp4) showing it.
An ok button may help.
however, this seems to be a normal HTML5 behaviour ...

**Comment by lucaslarroche** [comment]
Ok, thank you.

Yes, it's not really related to Pico. 
Pico only styles these default html components. There is no JavaScript to override default behavior.
