### ISSUE TITLE
Sass deprecation warnings

### ISSUE THREAD

**Issue by zgoda** [picocss/pico#27]
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($switch-width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
115 │       margin-left: calc(#{$switch-width / 2} - var(--border-width));
    │                           ^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@picocss/pico/scss/content/_form-checkbox-radio.scss 115:27  @import
    node_modules/@picocss/pico/scss/pico.scss 25:9                            @import
```

I believe this will require switching completely to dart-sass because node-sass won't support this syntax.

**Comment by lucaslarroche** [comment]
Thanks a lot for finding and fixing this bug (I'm not currently running Dart Sass 2.0.0).
I liked your first version with `* 0.5`.
I need to look more into it before merging your pull request.

**Comment by zgoda** [comment]
The 2nd commit fixes operator in 2 places that i messed up. The one place where `math.div()` is used may be also expressed with multiplication by fractional number, like 0.66666667 but i'm not familiar with CSS parser implementations to make informed decision whether this is acceptable or should be left for browser implementation to decide on precision of the result.

Using multiplication by fractional would make it compatible with `node-sass` and `libsass` in general, although [they both have deprecated status](https://sass-lang.com/blog/libsass-is-deprecated) for almost a year now.

**Comment by lucaslarroche** [comment]
Thank you!
I will probably merge soon.
But I want to run some tests first.
