### ISSUE TITLE
Add pico to the list of awesome-css-frameworks

### ISSUE THREAD

**Issue by stgeneral** [picocss/pico#30]
https://github.com/troxler/awesome-css-frameworks

**Comment by lucaslarroche** [comment]
Actually, I already created a [Pull Request](https://github.com/troxler/awesome-css-frameworks/pull/76) for Pico on `awesome-css-frameworks`.

You can upvote or comment to support the merge.

**Comment by stgeneral** [comment]
Updating done ;)
