### ISSUE TITLE
Breadcrumbs looks wrong on Safari

### ISSUE THREAD

**Issue by larstvei** [picocss/pico#331]
## Describe the issue

The slashes between items in are placed beneath the items, when rendering a with `aria-label="breadcrumb"`.

### Current Behavior
Using `aria-label="breadcrumb"` renders like this on Safari:

<img width="174" alt="Screenshot 2023-03-06 at 12 31 15" src="https://user-images.githubusercontent.com/2478638/223098636-fa2ced1b-43c2-4857-9ba0-15ab4b1dc908.png">

### Expected Behavior
It should render like it does on every other browser I have tried.

<img width="141" alt="Screenshot 2023-03-06 at 12 32 54" src="https://user-images.githubusercontent.com/2478638/223098926-0a6f6b8e-1a61-45c7-bbc4-27c74e012227.png">

### Reproduction URL

https://codepen.io/larstvei/pen/gOdxrBY

### Environment
Safari on MacOS and iOS

**Comment by purplespider** [comment]
It looks like it's the extra spaces you're putting in (before and after your opening and closing `a` tags) that is triggering this issue. If you take them out, it displays in Safari fine: https://codepen.io/purplespider/pen/xxaXqwv

**Comment by larstvei** [comment]
You are right! Thank you.

I will leave the issue open, as I do consider it to be buggy behavior. But feel free to close the issue.

**Comment by lucaslarroche** [comment]
I just pre-released the v2 🚀.
The breadcrumb has been revised.

Here is the documentation:
https://v2.picocss.com/docs/nav#breadcrumb

Other links:

- [Online documentation](https://v2.picocss.com/docs)
- [NPM pre-release](https://www.npmjs.com/package/@picocss/pico/v/2.0.0-alpha1)
- [GitHub pre-release](https://github.com/picocss/pico/releases/tag/v2.0.0-alpha1)
- [Website code](https://github.com/picocss/picocss.com)
- [v2 branch](https://github.com/picocss/pico/tree/v2)

**Comment by coffeeandwork** [comment]
This problem seems to show up on the demo site when viewed on safari: https://v2.picocss.com/docs/nav#breadcrumb
 
![Screenshot 2023-05-21 at 9 11 47 AM](https://github.com/picocss/pico/assets/6377739/2c1da2ff-d7f6-4cf3-bbf4-66e05011eb2d)

Safari Version: Version 16.4 (18615.1.26.110.1)

**Comment by alpheios** [comment]
It looked broken on Safari for me too.
For me this added CSS rule helped:

```
nav[aria-label=breadcrumb] li :where(a, [role=link]) {
  margin : unset;
  padding : unset;
}
```
