### ISSUE TITLE
Dropdown not aligned with other inputs in a grid

### ISSUE THREAD

**Issue by ypascal** [picocss/pico#338]
### Current Behavior
A concise description of the bug.
Hello,
Just noted a minor glitch : when mixing dropdowns  (<detail role="list">), with other elements (input, select...) in a grid, the fields are not aligned.
This occurs only when a <label> elements are wrapped around the dropdown.

![dropdownAlignment](https://user-images.githubusercontent.com/22128270/226197142-11ba4132-e5b6-45fb-ad5f-d8a78feb52dd.png)

### Expected Behavior
All elements that use the same syntax (element within a ```<label>``` element), should have the same margins.

### Proposed solution
See PR https://github.com/picocss/pico/pull/339

### Reproduction
```
        <div class="grid">
          <label for="Dropdown1">
            Dropdown
            <details role="list" >
              <summary aria-haspopup="listbox">Select an option</summary>
              <ul role="listbox">
                <li><a>Option1</a></li>
                <li><a>Option2</a></li>
              </ul>
            </details>
          </label>

          <label for="textfield1">
            Textfield
            <input type="text" id="Textfield1" name="Textfield1" placeholder="Blabla" required />
          </label>

          <label for="textfield1">
            Select
            <select>
              <option value="" disabled selected>Option 0</option>
              <option>1</option>
            </select>
          </label>
        </div>
```

### Environment
Example: OS, versions, browser details.

**Comment by ypascal** [comment]
See PR 339
https://github.com/picocss/pico/pull/339

**Comment by lucaslarroche** [comment]
Thank you. I will review and approve the PR, then ship it in v1.5.8
