### ISSUE TITLE
Slow animation in Safari browser

### ISSUE THREAD

**Issue by DaAitch** [picocss/pico#340]
## Describe the issue

Animation of a switch slider or an input field border color fade animation on focus is not smooth, especially if the screen gets larger.

Safari timelines:

Frames: <img width="200" alt="image" src="https://user-images.githubusercontent.com/1917071/228390421-9c1febae-2a83-4c51-ac89-2f18543c5e96.png">
Events: <img width="200" src="https://user-images.githubusercontent.com/1917071/228390824-4277c4f6-993f-4533-8023-88cb7e48682c.png">

### Current Behavior
Frame rate drops for animation

### Expected Behavior
Smooth like in Chrome and Firefox

### Reproduction URL
- https://picocss.com/examples/sign-in/
- press the "remember me" slider
- click into a text box

### Environment
- browser: Safari

**Comment by DaAitch** [comment]
Seems like webkit implementations are slow for

- `box-shadow` transition (click in input element)
- `margin` transition (switch)

**Comment by DaAitch** [comment]
I've updated MacOS from `MacOS 12.6.3, Safari 15.6.1` to `MacOS 13.3, Safari 16.4` and the performance issue is gone. I should have open this issue against webkit.

Thanks for listening :)

**Comment by pftg** [comment]
Hm, there is still an issue with animations: 

![Image](https://github.com/user-attachments/assets/c5079960-fe8d-4440-b4f8-21f74844c6c0)
