### ISSUE TITLE
v2.0.0 jsDelivr CDN link does not work

### ISSUE THREAD

**Issue by thiloho** [picocss/pico#347]
The jsDelivr CDN link for version 2 ([https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css](https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css)) is not working properly.

When navigating to the URL, the following error appears: **Couldn't find the requested release version 2.**

Here is a link to the relevant section in the new documentation: [https://v2.picocss.com/docs#install-from-cdn](https://v2.picocss.com/docs#install-from-cdn)

**Comment by lucaslarroche** [comment]
I just pre-released the `v2` 😎🚀

- [Online documentation](https://v2.picocss.com/docs)
- [NPM pre-release](https://www.npmjs.com/package/@picocss/pico/v/2.0.0-alpha1)
- [GitHub pre-release](https://github.com/picocss/pico/releases/tag/v2.0.0-alpha1)
- [Website code](https://github.com/picocss/picocss.com)
- [v2 branch](https://github.com/picocss/pico/tree/v2)
