### ISSUE TITLE
[Feature Request] Support classless version in module format

### ISSUE THREAD

**Issue by Amerr** [picocss/pico#362]
Please search for duplicate or closed issues first.
  
## Describe the issue
	Current installation via `yarn`or `npm` doesn't support classless feature, It would be good to have a support 
### Current Behavior
@import "@picocss/pico"; which is default

### Expected Behavior
`@import "@picocss/pico-classless";

**Comment by nakibrayan3** [comment]
to configure pico v2 you have to use the `@use` keyword inside a `scss` file

Here is an example to use the classless version:

```scss
@use "node_modules/@picocss/pico/scss/pico" with (
  $enable-semantic-container: true,
  $enable-classes: false
);
```

checkout the full tutorial in pico v2 docs: https://v2.picocss.com/docs/sass

**Comment by Amerr** [comment]
@nakibrayan3 I need to import in a regular CSS file.

**Comment by nakibrayan3** [comment]
to import pico from a CSS file, you have to download a files from here https://github.com/picocss/pico/tree/master/css , and then link to it from your html files.

**Comment by lucaslarroche** [comment]
I am closing this issue because it's possible to import the classless version with CSS or SCSS.
Thanks @nakibrayan3
