### ISSUE TITLE
Dropdown in nav on mobile not closing on click (Pico 2.0)

### ISSUE THREAD

**Issue by nibl** [picocss/pico#372]
## Describe the issue

In mobile browsers, dropdowns in navigation menus do not close after an item has been clicked. 
  

### Environment
Tested using current Pico 2.0 beta in MobileSafari on iOS.

**Comment by B-Esmaili** [comment]
AFAIK this is normal behavior. I think you have to manage it yourself using javascript.

**Comment by pjb3** [comment]
I was surprised by this behavior as well. I'm not sure if there is a better way to do this, but what I did was put an id on the details element, define a function to remove the open attribute from that element and then add that as a click handler to each link:

```svelte
<script>
  function closeMainNav() {
    document.getElementById("main-nav").removeAttribute("open")
  }
</script>

<details role="list" id="main-nav">
  <summary aria-haspopup="listbox" role="button">
    Links
  </summary>
  <ul role="listbox">
    <li><a href="/one" on:click={closeMainNav}>One</a></li>
    <li><a href="/two" on:click={closeMainNav}>Two</a></li>
    <li><a href="/three" on:click={closeMainNav}>Three</a></li>
  </ul>
</details>
```

This works, but feels a bit clunky. Is there a more elegant way to do this?

**Comment by jvoros** [comment]
I struggled with the same UI problem using the dropdown. Thanks for the code @pjb3.

I modified it to create  a general purpose dropdown close function that I can add to any `ul` tag, rather than every `li`. My site uses several dropdowns. Each dropdown can be closed using this event handler on the `ul` tag.

```javascript
function closeDropdown(event) {
      event.target.closest("details").removeAttribute("open");
    }
```
```html

<details role="list">
  <summary aria-haspopup="listbox" role="button">
    First Dropdown
  </summary>
  <ul role="listbox" on:click={closeDropdown}>
    <li><a href="/one">One</a></li>
    <li><a href="/two">Two</a></li>
    <li><a href="/three">Three</a></li>
  </ul>
</details>

<details role="list">
  <summary aria-haspopup="listbox" role="button">
    Second Dropdown
  </summary>
  <ul role="listbox" on:click={closeDropdown}>
    <li><a href="/one">One</a></li>
    <li><a href="/two">Two</a></li>
    <li><a href="/three">Three</a></li>
  </ul>
</details>
```

**Comment by CrlH** [comment]
This is not a PicoCSS issue. The state of the menu depends on the `open` attribute of your `<details>` tag. The toggle state will thus depend on whether or not your new (html) page render retained the `open` state for your tag. 

In a pure HTML environment, make user your `/linked-page.html` doesn't contain the the `open` attribute.
If you're using some type of framework that retains the `open` state, I'd suggest looking for the appropriate navigational lifecycle hook.

@jvoros & @pjb3 - from the syntax above, I assume you're both using Svelte(Kit). Based on your exact use-case, I'd suggest looking into [`beforeNavigate`](https://kit.svelte.dev/docs/modules#$app-navigation-beforenavigate) or [`afterNavigate`](https://kit.svelte.dev/docs/modules#$app-navigation-afternavigate).

**Comment by jvoros** [comment]
Thanks for the reply @CrlH 

I agree it is not a PicoCSS issue. 

I am using the dropdown for actions on the same page, so just like the modal, javascript is required to control the dropdown.

I also use it for links, but links that open in a new window. In that case returning to the original window still had the open dropdown after clicking the link. A little javascript can fix it.

My application uses Vue. But the code snippet above should work in any environment.

**Comment by lucaslarroche** [comment]
@B-Esmaili, @pjb3, @jvoros, @CrlH, thanks for the great comments.
I'm closing this issue.
