### ISSUE TITLE
v2: Links with aria-current="false" get the same treatment as if the link is for an active page

### ISSUE THREAD

**Issue by brianespinosa** [picocss/pico#415]
## Describe the issue

When creating a link with `aria-current` a link can have a style that matches hover and focus states for being active.
  
### Current Behavior
Currently, if `aria-current="false"` is set, the link will get style treatment as if it is active.

### Expected Behavior
When using `aria-current="false"` as a value, a link should not get style treatment as if it is active. Note that [`false` is marked as a valid value for `aria-current`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current#values).

### Reproduction URL
This can easily be seen in any codesandbox running Pico v2

### Environment
All environments. This is not unique to a specific browser.

**Comment by lucaslarroche** [comment]
Thanks ❤️
