### ISSUE TITLE
v2/docs: loading link example

### ISSUE THREAD

**Issue by gp-slick-coder** [picocss/pico#418]
![image](https://github.com/picocss/pico/assets/1906169/17b0a5a6-36d0-437f-b710-c2a158d4cb74)

In this example, I would take a different inline element. Showing a link that is not a link is ...

**Comment by lucaslarroche** [comment]
@gp-slick-coder, thanks. I updated the v2 docs:
<img width="944" alt="Screenshot 2024-02-18 at 13 26 04" src="https://github.com/picocss/pico/assets/23470684/7a91de9b-cf78-448e-92dd-fcf44ed2cb88">
