### ISSUE TITLE
aria-busy with tooltip unexpected rendering

### ISSUE THREAD

**Issue by Inveracity** [picocss/pico#423]
## Describe the issue

When tooltip and aria-busy are set on a button, the spinner looks funky

### Current Behavior

A gif showing a button with aria-busy + tooltip and another button with aria-busy and no tooltip

![output](https://github.com/picocss/pico/assets/8753040/de4fc8ef-3aa1-4e5c-aaee-6da4f48ed4f8)

### Expected Behavior

I expected the spinner to appear inside the button

### Reproduction

```html
<main class="container">
  <section>
    <p>"busy" button with tooltip</p>
    <button aria-busy="true" data-tooltip="hello world" data-placement="bottom" />
  </section>
</main>
```

### Environment
Pico CSS 1.5.11
Windows 10
Chrome Version 120.0.6099.130 (Official Build) (64-bit)

Thanks for making this awesome css framework

**Comment by lucaslarroche** [comment]
@Inveracity, I explored the problem, and it's impossible to fix, because both `[data-tooltip]` and `[aria-busy]` are using `::before`.
The fallback will be cleaner in the `v2`. `[aria-busy]` wins.

**Comment by Inveracity** [comment]
Thanks for taking a look, much appreciated. 
Excited for v2!
