### ISSUE TITLE
Form group with hidden input (Pico v2)

### ISSUE THREAD

**Issue by nicolas-brousse** [picocss/pico#425]
## Describe the issue
Not a game changer but since I've got this, I share it.

### Current Behavior
When creating a form group with text field and submit button that start with an hidden field, then the round on input text is not applied (since not first input tag).

### Expected Behavior
Having form group looks like in documentation.
https://v2.picocss.com/docs/forms#usage-with-group

### Reproduction URL
https://jsfiddle.net/ep6qtzcb/

### Environment
macOS 12.7.2, Firefox 121, Pico v2.0.0-rc1

**Comment by lucaslarroche** [comment]
@nicolas-brousse, I experimented more and didn't find a good solution that doesn't break other edge cases.
Let me know if you have any ideas.|

But you can use this:
```HTML
<form>
  <input type="hidden" name="token" value="123" />
  <fieldset role="group">
    <input type="email" placeholder="Enter your email" />
    <input type="submit" value="Subscribe" />
  </fieldset>
</form>
```

**Comment by nicolas-brousse** [comment]
@lucaslarroche thank you for your answer.
No worries. I would like to be helpful, but my css knowledge is too low to help, sorry.

However the solution you show is fine for me. I will do it like that.

Feel free to close this issue if you don't plan to go further.
