### ISSUE TITLE
v2: the selected options of an unfocussed select multiple element are not readable in dark mode

### ISSUE THREAD

**Issue by cmcaine** [picocss/pico#434]
## Describe the issue

In v2, the selected options of an unfocussed select multiple element are not readable in dark mode.

### Current Behavior

Focused:
![image](https://github.com/picocss/pico/assets/6000761/99abf30e-8c2e-4ad9-b30e-d2a6287ec964)

Unfocused:
![image](https://github.com/picocss/pico/assets/6000761/53b15e83-0a0e-40cb-8ebe-2e936f0ab994)

### Expected Behavior

To be able to read the selected options when the select element is not focused.

### Reproduction URL

https://v2.picocss.com/docs/forms/select#multiple

### Environment
Windows, Firefox 121.0.1

**Comment by lucaslarroche** [comment]
@cmcaine I couldn't see the problem on MacOS/iOS Chrome/Firefox.
This light blue color is very weird 🤷‍♂️

It would be ideal if someone could help me debug/find the problem.

**Comment by Brian-Pob** [comment]
I did some testing on MacOS, Arch Linux, and Windows 11 (Browserstack). I was able to reproduce the issue on Windows 11 with Firefox versions 121 and 122 (latest version). I used [Browserstack](https://www.browserstack.com/) for some quick testing but I have access to Windows machines that I can do further testing on.


|            | FF 121     | FF 122       |
|------------|------------|--------------|
| MacOS      | Did not test         | Not reproduced  |
| Arch Linux | Did not test         | Not reproduced  |
| Windows 11 | Reproduced | Reproduced   |


![Screenshot of firefox 121 on browserstack](https://github.com/picocss/pico/assets/29676413/6535191a-f4ef-44d8-ad5f-05a61598fad2)
*Firefox 121*
---


![Screenshot of firefox 122 on browserstack](https://github.com/picocss/pico/assets/29676413/97fa8827-2c7a-430a-949a-46d4737a9fdb)
*Firefox 122*
---

**Comment by lucaslarroche** [comment]
Thanks @Brian-Pob!

I tried to force the color on the checked options.
Could you check that this fixes the problem?
https://codepen.io/lucastests/pen/NWJJNVy

**Comment by Brian-Pob** [comment]
That seems to have fixed it! Tested on Windows 11 on Firefox 122.0.1

https://github.com/picocss/pico/assets/29676413/b42b0f2a-2b8a-43e4-b618-7928a8570bc3

**Comment by Brian-Pob** [comment]
Also tested on Chrome and Edge on Windows 11. No issues found.

https://github.com/picocss/pico/assets/29676413/3aaa79f3-fa0c-47f4-8756-9b17395c4106
