### ISSUE TITLE
Missing Theme Builder

### ISSUE THREAD

**Issue by resistdesign** [picocss/pico#438]
Please search for duplicate or closed issues first.
  
## Describe the issue
The minimum theme generator was very useful but it's now missing from: https://v2.picocss.com/docs/theme-generator
![image](https://github.com/picocss/pico/assets/356375/ccb222c2-de2d-4547-be8c-97e98442f4a4)
  
### Current Behavior
A concise description of the bug.
It's a 404

### Expected Behavior
A concise description of what you expected.
The theme builder should still be there.

### Reproduction URL
We recommend including a link to a minimal reproduction of the bug using CodePen or a similar tool.
**Please do not link to your actual project.** Instead, we need a reduced test case in a new project without any unnecessary code.

https://v2.picocss.com/docs/theme-generator

### Environment
Example: OS, versions, browser details.

All

**Comment by lucaslarroche** [comment]
@resistdesign,
I just added the redirect from https://v2.picocss.com/docs/theme-generator to https://v2.picocss.com/docs/version-picker
You now have the 20 color themes in separate .css file.
And if you want to see a complete example for CSS customization, you can go to https://v2.picocss.com/docs/css-variables, then "Detailed example to override the primary color".

**Comment by resistdesign** [comment]
Ah I see how that works now! Awesome!
