### ISSUE TITLE
Update form elements to use `:invalid` for HTML5 pattern and validation requirements

### ISSUE THREAD

**Issue by ajusa** [picocss/pico#47]
See https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid

Right now, there is aria-invalid="false" and aria-invalid="true" but those aren't automatically applied by the browser when a form element has invalid input. Ideally, if I don't have a valid email in an email input, it will gain the same look as the aria-invalid="true" styles.

**Comment by abouthalf** [comment]
Hello! I would like to revisit this issue. :user-valid and :user-invalid are both widely available in modern browsers and are only applied once the user has interacted with the element - that should eliminate the issue above and remove the requirement for JavaScript twiddling and noodling

See: https://developer.mozilla.org/en-US/docs/Web/CSS/:user-invalid#browser_compatibility

**Comment by bobby** [comment]
@abouthalf I've added a new issue #621 to add support for `:user-valid` and `:user-invalid` as you propose (and I heartily agree!).
