### ISSUE TITLE
`code` tag should keep whitespace

### ISSUE THREAD

**Issue by 8ctopus** [picocss/pico#545]
## Describe the issue

The `code` tag does not respect whitespace.

```html
<code>
[
    {
        "id": "PROD-7LE34802UJ0769203",
        "name": "test product",
        "description": "test description",
        "create_time": "2023-10-11T11:46:02Z"
    }
]
</code>
```

![2024-05-22_110602](https://github.com/picocss/pico/assets/13252042/623f93a0-d06c-472f-aba2-a989cb01d14c)

### Expected Behavior

Respect whitespace so that the code is nicely formatted.

### Reproduction URL

https://codepen.io/8ct8pus/pen/wvbGLYO

### Environment

Windows 10 Pro, Edge Version 125.0.2535.51 (Official build) (64-bit)

**Comment by 8ctopus** [comment]
on a side note, it would be good to add it to the doc as well

**Comment by shuuji3** [comment]
How about using the standard `<pre>` block element, instead of `<code>` inline element, for multiple lines of code block?

ref. https://developer.mozilla.org/docs/Web/HTML/Element/pre

**Comment by stuartmaxwell** [comment]
Yes, @shuuji3  is correct. `<pre>` is the correct element to use if you want to preserve whitespace. You can either replace the `code` element with a `pre` element, or if you _need_ to use `code` for some reason, you can wrap your `code` element with a `pre` element.

Option 1:

```html
<pre>
[
    {
        "id": "PROD-7LE34802UJ0769203",
        "name": "test product",
        "description": "test description",
        "create_time": "2023-10-11T11:46:02Z"
    }
]
</pre>
```

Option 2:

```html
<pre><code>
[
    {
        "id": "PROD-7LE34802UJ0769203",
        "name": "test product",
        "description": "test description",
        "create_time": "2023-10-11T11:46:02Z"
    }
]
</code></pre>
```

Note that the `pre` element will retain all whitespace, including the line breaks before and after the `pre` tags. So you would probably want to use the following to remove the starting and ending line breaks:

```html
<pre>[
    {
        "id": "PROD-7LE34802UJ0769203",
        "name": "test product",
        "description": "test description",
        "create_time": "2023-10-11T11:46:02Z"
    }
]</pre>
```

**Comment by 8ctopus** [comment]
@shuuji3 @stuartmaxwell Thank you guys for your feedback and I apologize for my ignorance.
