### ISSUE TITLE
[Feature Request] Browser compatibility?

### ISSUE THREAD

**Issue by izzygld** [picocss/pico#76]
Would be nice to have in the Docs what the Browser compatibility is like (especially because you are using `Grid` and `:not` for an example)

thanks.

**Comment by lucaslarroche** [comment]
Hi @izzygld, 

To be honest, I'm not sure how to test this properly.
I tend to be very careful with the CSS selectors (checking [Caniuse](https://caniuse.com/) a lot).
I also compile Pico with some [autoprefixer](https://github.com/picocss/pico/blob/master/package.json#L85), [browser list here](https://github.com/picocss/pico/blob/master/package.json#L98).

Do you have an idea of the process to check the global Browser compatibility for Pico?

**Comment by lucaslarroche** [comment]
I added explicit Browser support in the README, which **excludes IE**.
https://github.com/picocss/pico/tree/dev#browser-support
It will be shipped in the [next release](https://github.com/picocss/pico/pull/155).
