### ISSUE TITLE
[Change Request] Remove explicit background-color on tr element

### ISSUE THREAD

**Issue by myth** [picocss/pico#78]
Hi,

What do you think about removing the explicit `background-color: var(--background-color)` on the `<tr>` element?

Right now tables don't play nicely with `<article>` in dark mode, as the background colors differ, the table sticks out quite abruptly.
In light mode, the main section of an `<article>` is already white, so the white background color doesn't make a difference.

Could a simple solution be to let `<tr>` be transparent, but keep:

```
table[role="grid"] tbody tr:nth-child(2n+1) {
  background-color: var(--table-row-stripped-background-color);
}
```

At first glance it seems to maintain existing behaviour in light mode, and give a similar aesthetic also in dark mode inside an `<article>`

**Comment by lucaslarroche** [comment]
Hi @myth, 
I agree. Nice find.
I will ship this small change in the next release.

**Comment by myth** [comment]
Great, thanks!
