### ISSUE TITLE
[Feature request] CSS variables for label font-weight

### ISSUE THREAD

**Issue by dylanvdmerwe** [picocss/pico#79]
If we have a login page, or general form such as this:
![image](https://user-images.githubusercontent.com/2852839/147209796-98efee97-361f-4e84-9211-a246ddf36c84.png)

It would be great to be able to control the form control font-weights so they stand out a bit more. 

![image](https://user-images.githubusercontent.com/2852839/147210207-81a4008b-4406-4fbf-8a6f-7a174bcce7b9.png)

Currently the labels are using:
![image](https://user-images.githubusercontent.com/2852839/147210085-118721c0-7a96-4d2d-85bb-becb408ce1d2.png)

So if `--font-weight` is adjusted, all the fonts on the page are changed. 

Could we have different kinds of variables for labels on forms to control the weights in pico without having to override styles?

**Comment by HerrBertling** [comment]
You could even do <code>font-weight: var(--label-font-weight, var(--font-weight))</code> so that this wouldn't even be a breaking change – the fallback for the label font weight would just™ be what is used right now :blush:

**Comment by jubishop** [comment]
Why not just create the PR?

**Comment by HerrBertling** [comment]
Sorry, worked on `master` initially instead of `dev`. The last two commits should be the correct ones 🙈

**Comment by lucaslarroche** [comment]
Thank you @HerrBertling. I like the addition.
