### ISSUE TITLE
Feature request - file upload component

### ISSUE THREAD

**Issue by lindig** [picocss/pico#84]
I would be interested in a component that supports drag-and-drop file upload. Typically you can either select a file for upload by browsing or drop an existing file onto a "drop" area. I believe the component is universal enough to warrant consideration. It's usability depends quite a bit on the styling and hence why this is a good candidate for inclusion.

**Comment by lucaslarroche** [comment]
`<input type="file">` natively supports the Drag and Drop.
We can design a Drag and Drop area, but this would require some `.classes` and probably some javascript to manage all the states (no file, drag and drop hover, errors, etc.)
I prefer to keep the native `<input type="file">` without addition for now.
But I'm always open to suggestions and codes example (without Javascript, ideally).

**Comment by lindig** [comment]
Fair enough. I understand the desire to keep JavaScript out. A visually attractive drag-and-drop area would go a long way already. Is selector `input[type=file]` enough to style it without classes?
