### ISSUE TITLE
SVG in menu blocks documentation on Firefox

### ISSUE THREAD

**Issue by jimgregory** [picocss/pico#9]
The SVG icon in the menu on the documentation page completely blocks the screen on Firefox 68.12 ESR.  
Here is the screenshot:

![Screenshot_2020-10-25_Documentation-Pico_css](https://user-images.githubusercontent.com/12471780/97104724-15131b80-1684-11eb-8c46-2b7d14f1e8c4.png)

I think the problem is the Github icon has its `height` set to `1rem`.  On [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Content_type#Length), `rem` is not among the list of valid SVG length property units (which would explain why I'm getting several height errors in my browser console when I load the docs).  

FWIW, if I change `1rem` to `1em`, the docs load OK.

**Comment by lucaslarroche** [comment]
I downloaded Firefox 68.12 ESR but I don't see this bug.
Is it on Windows or Mac?
But yes, you're right, we should define the height in CSS.

**Comment by jimgregory** [comment]
I'm using Debian Linux.

**Comment by lucaslarroche** [comment]
Most probably I will:
- define in `px` in HTML (`16px`)
- override in `rem` in CSS (so it follows the responsive typography size)

I will check both [pico/](https://github.com/picocss/pico) and [examples/](https://github.com/picocss/examples)

Thanks for the report.

**Comment by lucaslarroche** [comment]
@jimgregory, I edited the docs in the [dev/](https://github.com/picocss/pico/tree/dev) branch.
Can you check if the bug is fixed: https://picocss.github.io/pico/docs/index.html

**Comment by jimgregory** [comment]
Looks perfect!  Thanks for taking care of this.  I'll mark this issue closed.

**Comment by lucaslarroche** [comment]
Thanks for checking.
I keep this ticket open until I publish the changes to the `master` branch.
