### ISSUE TITLE
[Change Request] Do not use hgroup

### ISSUE THREAD

**Issue by AmiralBl3ndic** [picocss/pico#90]
Hello.
First of all, thanks for the amazing product, it is a breeze to use for prototyping applications!

I am using the `hgroup` tag for grouping heading tags together as explained in the documentation but something bugs me: hgroup is not an HTML5 standard.
This is problematic because it makes using it very complicated with Vuejs for example: using `hgroup` with Vue + Vite results in build errors (`TS2604`).

Maybe for this specific use case it could be better of using non purely semantic but instead relying on classes?

i.e., this:
```html
<hgroup>
    <h1>Hello</h1>
    <h2>World</h2>
</hgroup>
```

could become this:
```html
<div class="headings">
    <h1>Hello</h1>
    <h2>World</h2>
</div>
```

Thanks again! 🚀

**Comment by lucaslarroche** [comment]
Also solve #32
