### ISSUE TITLE
Correction for the Switch button

### ISSUE THREAD

**Issue by cara-tm** [picocss/pico#92]
When checked, the circle of the switch button is positioned on the edge without a thin space as when it isn't checked.

This little amendment corrects this:

    [type="checkbox"][role="switch"]:checked::before {
        margin-left: auto;
        ...
    }

Now, to allow sizing changes for these kinds of buttons (switch & radio) -no Framework offer it-, adding this make the trick:

    [type="checkbox"], [type="radio"] {
        font-size: inherit;
    }

**Comment by lucaslarroche** [comment]
> When checked, the circle of the switch button is positioned on the edge without a thin space as when it isn't checked.
> 
> This little amendment corrects this:
> 
> ```
> [type="checkbox"][role="switch"]:checked::before {
>     margin-left: auto;
>     ...
> }
> ```

I can't see the problem on my side.
<img width="281" alt="Screen Shot 2021-12-31 at 15 19 49" src="https://user-images.githubusercontent.com/23470684/147811975-9df48382-30ae-4c2e-8559-ad1a1be4ffa4.png">

Can you detail your environment (device, os, browser)?

**Comment by lucaslarroche** [comment]
> Now, to allow sizing changes for these kinds of buttons (switch & radio) -no Framework offer it-, adding this make the trick:
> 
> ```
> [type="checkbox"], [type="radio"] {
>     font-size: inherit;
> }
> ```

Nice one. I will definitively add it.

**Comment by cara-tm** [comment]
Yep. Sorry, you're right for the border ;)

**Comment by cara-tm** [comment]
I finally found where the problem occurs:

    [type="checkbox"][role="switch"]:checked::before {
        /* margin-right: 0; Not necessary: to be removed */
        /* correct margin left calculation for the circle placement: input width - circle diameter */
        margin-left: calc(2.25em - 1.25em);
        ...
    }

**Comment by lucaslarroche** [comment]
@cara-tm I still don't see any problems here 😐
What is your browser?
You are right for `margin-right` is not needed.

**Comment by lucaslarroche** [comment]
I'm reopening the issue until we're sure
